# Generated by Django 4.2.5 on 2025-01-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doctor',
            new_name='doctor_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='patient',
            new_name='patient_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tmc_operator',
            new_name='tmc_operator_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='practice_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='village',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_experience',
        ),
    ]
