# Generated by Django 4.2.5 on 2025-01-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_doctor_user_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verify_phone',
            field=models.BooleanField(default=False),
        ),
    ]
