# Generated by Django 4.2.5 on 2025-01-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
