# Generated by Django 4.2.5 on 2025-03-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doctor_user',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_verify_email',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verify_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patient_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tmc_operator_user',
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
