# Generated by Django 4.2.5 on 2025-01-05 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_doctor_user_doctor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMC',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tmc/photos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='tmc/document/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
