# Generated by Django 4.2.5 on 2025-03-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_rename_doctor_user_user_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('pending', 'Pending'), ('completed', 'Completed')], default='assigned', max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('ssigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
