# Generated by Django 4.2.5 on 2025-03-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='ssigned_to',
            new_name='assigned_to',
        ),
    ]
